---
name: Checks

on:
  push:
  pull_request:

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Run flake8
        run: docker compose run --rm app sh -c "flake8"
